BussinessGamess/BussinessGamess/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings


urlpatterns = [
    path('',include('core.urls')),
    path('',include('catalogo_personal.urls')),
    path('',include('catalogo_general.urls')),
    path('admin/', admin.site.urls),
    path('',include(('core.urls','core'), namespace='core')),
    path('',include(('catalogo_personal.urls','catalogo_personal'),namespace='personal')),
    # Paths de auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

BussinessGamess/core/urls.py
from django.urls import path
from .views import HomePageView ,BasePageView,BienvenidaPageView
from django.contrib.auth.decorators import login_required, permission_required

#manejo urls de cada vista
urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('', BasePageView.as_view(), name="base"),
    path('bienvenida/', login_required(BienvenidaPageView.as_view()),name="bienvenida"), 
]

BussinessGamess/core/models.py
from django.db import models

# Create your models here.

BussinessGamess/catalogo_general/forms.py
from django import forms
from .models import Comentarios

class ComentariosForm(forms.ModelForm):
    class Meta:
        model = Comentarios
        fields = ('text',)

class SearchForm(forms.Form):
    nombre = forms.CharField(max_length=100,required=False)

BussinessGamess/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from catalogo_personal.models import Videojuegos
from django.views.generic import CreateView, DetailView, ListView
from django.db.models import Avg

# Create your views here.
#vista del home
class HomePageView(ListView):
    template_name = "core/home.html"
    model = Videojuegos
    context_object_name = 'videojuegos'
    def get_queryset(self):
        return Videojuegos.objects.only('title','image','categoria','id').annotate(Avg('votacion__valor_votacion')).filter(votacion__valor_votacion__avg__range=(4,5))

class BasePageView(TemplateView):
    template_name = "core/base.html"
    
    def get(self,request,*args,**kwaegs):
        return render(request,self.template_name,{'title': "BusinessGames"})

#vista de bienvenida cuando el usuario se registea con exito
class BienvenidaPageView(TemplateView):
    template_name = "core/bienvenida.html"

    @method_decorator(login_required)
    def get(self,request,*args,**kwaegs):
        return render(request,self.template_name,{'title': "Bienvenida"})

BussinessGamess/core/templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
  {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/style_stars_rating.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/style_catalogo_general.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'notificaciones/css/styless.css' %}">



<title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbarHome">
      <div class="row align-items-center justify-content-between">
        <div class="col-md-1">
           <a  href="{% url 'general' %}" class="material-icons home_button">home</a>
        </div>
        <div class="col-md-6">
          <div id="buscador" class="input-group">
            <input id="inputBuscador" id="id_nombre" name="nombre" type="text" class="form-control" placeholder="Busca el repuesto por nombre o referencia" aria-label="Busca el repuesto por nombre o referencia" aria-describedby="button-addon2">
            <div class="input-group-append sectionIconBuscador">
              <button  for="nombre" class="btn btn_buscador" type="button" id="button-addon2">
                <i class="material-icons search_button">search</i>
              </button>
            </div>
          </div>
        </div>
        <div class="col-md-3 ">
        {% if not request.user.is_authenticated %}
          <ul class="navbarHomeList">
            <li class="navbarHomeListItem"><a href="{% url 'login' %}">Iniciar sesión</a></li>
            <li class="navbarHomeListItem"><a href="{% url 'registro' %}">Registrarte</a></li>
          </ul>
        </div>
        {% else %}
        <div class="col-md-17">
        <div  style="margin:0 auto;width:900px">
            <ul id="nav">
              <li id="notification_li">
                <span id="notification_count">3</span>
                <a href="#" style= "color: rgb(245, 244, 244);" class= "noti" id="notificationLink">Notifications</a>
                <div id="notificationContainer">
                  <div id="notificationTitle">Notifications</div>
                  <div id="notificationsBody" class="notifications">
                    
                  </div>
                        <div id="notificationFooter"><a href="#">See All</a></div>
                    </div>
                </li>
            </ul>
        </div>
         <div class="imgBox">
            <a  
              href=""
              data-toggle="dropdown" 
              aria-haspopup="true" 
              aria-expanded="false"
              class="linkImgPerfil">
              <img 
                class="imgProfile dropdown-toggle" 
                src="{% static 'pacho/assets/man.png' %}" >
            </a>  
            <div class="dropdown-menu dropdown-menu-right">
              <a href="{% url 'videojuego' %}"><button class="dropdown-item" type="button">Subir videojuego</button></a>
              <a href="{% url 'catalogo' %}"><button class="dropdown-item" type="button">Ver catálogo</button></a>
              <a href="{% url 'logout' %}"><button class="dropdown-item cerrarSesionLink" type="button">Cerrar sesión</button><a/>
            </div>
          </div>
        </div>
        {% endif %}
      </div>
    </nav>
<!-- Contenido -->
    {% block content %}{% endblock %}
    <script src="{% static 'catalogoG/js/and.js' %}"></script>
    <script src="{% static 'notificaciones/js/noti.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block js %} {% endblock %}
  </body>
</html>

BussinessGamess/core/templates/core/bienvenida.html
{% extends 'core/base.html' %}{% block title %}Bievenido{% endblock %}
</ul> {% block content %}{% if 'register' in request.GET %}
<p style="color:green">Usuario registrado correctamente , ya puedes identidicarte</p> {% endif %} {% if user.is_authenticated %}
<h1>BIENVENIDO {{ user.username }}</h1>
{% else %}
<a href="{% url 'registro' %}">Registrate</a> {% endif %} {% endblock content %}

BussinessGamess/core/templates/core/home.html
{% extends 'core/base.html' %} {% load static %} {% block title %}Inicio{% endblock %} 
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/style_stars_rating.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pacho/css/style_catalogo_general.css' %}">

  </head>
  <body>
     {% block content %}
		<div class="mainContent container-fluid">
      <div class="row justify-content-center">
        <div class="col-8">
          <div class="titleDiv">
	         <img class="logo_login" src="{% static 'pacho/assets/bg_logo.png' %}">
	    		 <h1 class="welcome_text">Lo mas destacado de la semana</h1>
          </div>
          <div class="vgSection">
            <div class="row justify-content-center">
              <div class="col-7">
              {% for video in videojuegos %}
              <a href="{% url 'detalles' video.id %}">
                <div class="vgCard">
                  <div class="container-fluid">
                    <div class="row align-items-center">
                      <div class="vgImage">
                        <img class="vgImg" src="{{video.image.url}}">
                      </div>
                      <div class="vgDetails">
                        <h3 class="vgTitle">{{video.title}}</h3>
                        <div class="col-md-12 ">
                          <fieldset class="rating desktop-display-important pt-0">           
                            <div class="vgImage ">
                                <img class="vgImg " src="{% static 'pacho/assets/star.png' %}">
                                <div class="col-8"><h3  class="vgTitle">{{video.votacion__valor_votacion__avg}}</h3></div>
                            </div>
                          </fieldset>

                        </div>
                      </div>
                    </div>
                  </div>
      		    	</div> 
                </a>
                {% endfor %}                            
              </div>  
            </div>
          </div>
		    </div>
    	</div>
  	</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}